version: '3.7'

services:
  to-do-user:
    image: to-do-user
    ports:
      - "8100:8100"
    networks:
      - to-do-app-network
    depends_on:
      - mysqldb
      - naming-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'

  to-do-app:
    image: to-do-app
    ports:
      - "8200:8200"
    networks:
      - to-do-app-network
    depends_on:
      - mysqldb
      - naming-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'

  naming-server:
    image: naming-server
    ports:
      - "8761:8761"
    networks:
      - to-do-app-network


  api-gateway:
    image: api-gateway
    ports:
      - "8765:8765"
    networks:
      - to-do-app-network
    depends_on:
      - naming-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'


  mysqldb:
    image: mysql:8
    networks:
      - to-do-app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=to_do_app

networks:
  to-do-app-network: